language: cpp

sudo: required

compiler:
 - gcc

env:
  global:
   - WINEDEBUG=-all

before_install:
 - sudo apt-get update -qq && sudo apt-get install -yqq wine

script:
 - make CC=i586-mingw32msvc-g++ WINDRES=i586-mingw32msvc-windres LDFLAGS=-lwinmm
 - file -i mouseclicker.exe

after_success:
 - wine mouseclicker.exe
