language: cpp

sudo: required

compiler:
 - gcc

before_install:
 - sudo apt-get update -qq && sudo apt-get install -yqq wine

script:
 - i586-mingw32msvc-g++ mouseclicker.cpp -o mouseclicker.exe -g -Wall -lwinmm
 - file -i mouseclicker.exe
 - wine mouseclicker.exe
