language: cpp

compiler:
 - gcc

before_install:
 - apt-get update && apt-get install -y wine

script:
 - i586-mingw32msvc-g++ mouseclicker.cpp -o mouseclicker.exe -g -Wall -lwinmm
 - file -i mouseclicker.exe
 - wine mouseclicker.exe
